apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoramento
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limitamonitoramento
spec:
  limits:
  - default:
      cpu: 500m
      memory: 256Mi
    defaultRequest:
      cpu: 250m
      memory: 128Mi
    type: Container