apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvlocal
  namespace: wordpress
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /opt/dados
    server: 192.168.100.230
    readOnly: false
