on: workflow_dispatch
name: Enviar imagem
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

      # Login no azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.ACESSO_AZURE }}

    - uses: azure/docker-login@v1
      with:
        login-server: dukercsmcr1.azurecr.io
        username: ${{ secrets.acr_dukercsmcr1_username }}
        password: ${{ secrets.acr_dukercsmcr1_password }}



    # - name: Build and push image to ACR
    #   id: build-image
    #   run: |
    #     docker build "$GITHUB_WORKSPACE/imagem" -f  "imagem/Dockerfile" -t dukercsmcr1.azurecr.io/wordpressaks:1.10 --label dockerfile-path=imagem/Dockerfile
    #     docker push dukercsmcr1.azurecr.io/wordpressaks:1.10

    - uses: azure/setup-kubectl@v1
      id: install 

    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_wordpressaks_kubeConfig }}
      id: login

    - name: lista dir
      run: | 
        ls
        sleep 2

    - name: Criar ambiente wordpress com kustomize
      run: |
        az aks command invoke \
        --resource-group wordpressrg \
        --name wordpress-aks \
        --command "kubectl apply -k ./"

    # - name: Instalar loki
    #   run: |
    #     az aks command invoke \
    #     --resource-group wordpressrg \
    #     --name wordpress-aks \
    #     --command "helm upgrade --install loki --version 2.6.5 --namespace=monitoramento grafana/loki-stack --create-namespace"

    # - name: Aguardar loki
    #   run: |
    #     az aks command invoke \
    #     --resource-group wordpressrg \
    #     --name wordpress-aks \
    #     --command "while [[ $(kubectl -n monitoramento get pods -l app=loki -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "waiting for pod" && sleep 1; done"

    # - name: Instalar prometheus com values.yaml
    #   run: |
    #     az aks command invoke \
    #     --resource-group wordpressrg \
    #     --name wordpress-aks \
    #     --command "helm upgrade --install prometheus --version 36.2.0 --namespace monitoramento prometheus-community/kube-prometheus-stack -f values.yaml"