on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: dukercsmcr1.azurecr.io
        username: ${{ secrets.acr_dukercsmcr1_username }}
        password: ${{ secrets.acr_dukercsmcr1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/imagem" -f  "imagem/Dockerfile" -t dukercsmcr1.azurecr.io/wordpressaks:${{ github.sha }} --label dockerfile-path=imagem/Dockerfile
        docker push dukercsmcr1.azurecr.io/wordpressaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_wordpressaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep wordpress-aksbb54 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace wordpress-aksbb54`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: wordpress-aksbb54
        container-registry-url: dukercsmcr1.azurecr.io
        container-registry-username: ${{ secrets.acr_dukercsmcr1_username }}
        container-registry-password: ${{ secrets.acr_dukercsmcr1_password }}
        secret-name: wordpressaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: wordpress-aksbb54
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          dukercsmcr1.azurecr.io/wordpressaks:${{ github.sha }}
        imagepullsecrets: |
          wordpressaksdockerauth
